### PR TITLE
Pure bash implementation of AWS DynDNS

### PR DESCRIPTION
**Pull request by chuckwolber**
Added a pure bash option for embedded systems that are unable to support a full AWS CLI. Also added an install script and updated the documentation.

### CODE REVIEW

**Comment by famzah** [comment]
Hi Chuck. Thank you for the contribution. Your code looks great and I'm merging it.

I have one note. To keep things simple, instead of embedding the alternative AWS CLI implementation I would have created a separate script which accepts (almost) the same arguments. In this case that would be `aws route53 change-resource-record-sets`. The standard CLI accepts JSON while you send XML via Curl but we can easily extract the information in the JSON using the command `jq`. Alternatively, the `aws-dyndns` script could call the alternative CLI and provide all arguments as positional ones, if the standard `aws` command is not available. This leaves `aws-dyndns` very easy to read and audit, while also makes the alternative AWS CLI implementation easy to develop and test on its own.

**Comment by chuckwolber** [comment]
Hi Famzah - Thank you!

I really like your idea for using `jq` to extract the data and generate XML for the curl command and I can confirm that the `jq` command appears in the basic install of the current EdgeOS (v2.0.9).

I also like your idea of separating the curl version into a separate file to keep `aws-dyndns` easy to read and audit. I had originally considered doing it that way, but I was worried that putting things into separate files would end up duplicating functionality. But your idea for using `jq` solves most of that.

As you alluded, I can just call the script something like `aws-curl` and accept the exact same arguments we are passing to the `aws` command. Then in the `aws-dyndns` `main()` function, I can set an `AWS_CLI_COMMAND=` variable to `aws` or `aws-curl`. Then the pollling loop never has to do a check, it simply executes a function that assembles the JSON and calls `${AWS_CLI_COMMAND} route53 change-resource-record-sets --hosted-zone-id "${AWS_ZONE_ID}"  --change-batch "${AWS_JSON_CMD}"`.

Inside of `aws-curl` I would use `jq` to turn the JSON into XML, and the rest is already done.

And now that I am thinking about this even further, that idea opens the can of worms to a different question - `aws-curl` could start out as a "one trick route53 pony" but this approach somewhat implies that it _could_ start collecting other AWS CLI functionality for use in embedded IoT devices that have limited resources.

Given that - what do you think about this idea? What if we treat the AWS CLI as a plugin in `aws-dyndns`? I think all we would need to do is add a configuration variable `AWS_CLI_COMMAND=` to `aws-dyndns.conf` and make sure that it was consumed within `aws-dyndns`, and default it to `aws` if it was not found/unset.

In that way, if you want a pure bash AWS CLI for a constrained environment, you install my project and make the config change for `aws-dyndns` in `/etc/aws-dyndns.conf`.

I can start working on a patch for the plugin approach if you are ok with the general idea.

**Comment by famzah** [comment]
Hi. I had doubts if `jq` is available. Now that we know, I have a more robust proposal.

Refactor `aws-curl` into a separate GitHub project and then simply symlink it on EdgeOS as `aws` (/usr/local/bin/aws -> /usr/local/bin/aws-curl). This way `aws-dyndns` will never need to know if the full-featured or the Bash-only AWS CLI is installed. Because we always call `aws` and both implementations accept the same arguments.

AWS CLI is already an external dependency of `aws-dyndns`. So it's up to the system administrator to install the official AWS CLI or the pure Bash alternative implementation.

_P.S._ You can definitely implement other AWS CLI commands, if you need to.

**Comment by chuckwolber** [comment]
Great idea. I will set up a separate `aws-curl` project and send you a pull request when I am ready.

**Pull request merged**
